### ISSUE TITLE
Gate driver missing

### ISSUE THREAD

**Issue by alberto-cesare** [jsphuebner/inverter-hardware#1]
Hi Johannes,

thanks for sharing this amazing work.
I noticed that gate driver board, schematic and bom is missing from the repo.
I found the schematic on your site, but there is no name for the DC/DC converter and the pcb.
Can you please upload this design?

Many many thanks!
Alberto

**Comment by jsphuebner** [comment]
Hi Alberto,

thanks for pointing it out. I added the part numbers and uploaded the files to the repo.

Johannes

**Comment by alberto-cesare** [comment]
Thanks Johannes,

you have been very fast, thank you!
