### ISSUE TITLE
Add License file

### ISSUE THREAD

**Issue by DOSputin** [jsphuebner/inverter-hardware#3]
A `LICENSE` including the full language of the chosen licensing scheme should be included as a separate file in the code repository.

**Comment by DOSputin** [comment]
Reading the CC license, it says

> indicate the Licensed Material is licensed under this Public License, and include the text of, or the URI or hyperlink to, this Public License.

So it seems that putting the link in to the README satisfies this particular license terms.  

will close issue now.

**Comment by jsphuebner** [comment]
Very good, less to do :) Thanks.
